server:
  port: 8082
spring:
  application:
    name: spring-cloud-loadbalancer-openfeign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

service:
  spring-cloud-loadbalancer-server: spring-cloud-loadbalancer-server