spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_unit_test
    username: root
    password: 12345678

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/sqlmap/*.xml
  type-aliases-package: me.cxis.unit.test.junit5.dao.model