server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    instance-id: spring-cloud-gateway-server
    hostname: spring-cloud-gateway-server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway