dubbo:
  application:
    name: sentinel-provider
  registry:
    url: localhost:2181
  provider:
    port: 20880
    version: LATEST
    retries: 0
    timeout: 1000

project:
  name: sentinel-provider