server:
  port: 8080

spring:
  application:
    name: spring-boot-actuator-datasource
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_actuator_datasource
    username: root
    password: 12345678
  jmx:
    enabled: true

management:
  endpoints:
    # 启用所有端口
    enabled-by-default: true
    web:
      exposure:
        # 暴露所有端口
        include: "*"