server:
  port: 8081
spring:
  application:
    name: default-httpclient-client-core
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

service:
  default-httpclient-server: default-httpclient-server-core