spring:
  application:
    name: grpc-nacos-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          gRPC:
            port: ${grpc.server.port}
grpc:
  server:
    port: 9898
server:
  port: 8081