server:
  port: 8080
spring:
  application:
    name: grpc-nacos-client
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
grpc:
  client:
    grpc-nacos-server:
      negotiationType: plaintext


logging:
  level:
    net:
      devh:
        boot:
          grpc:
            client:
              nameresolver:
                DiscoveryClientNameResolver: debug