server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          # 匹配所有请求
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: spring-cloud-gateway-service-1
          uri: lb://spring-cloud-gateway-service-1
          predicates:
            - Path=/s1/**
          filters:
            - StripPrefix=1
        - id: spring-cloud-gateway-service-2
          uri: lb://spring-cloud-gateway-service-2
          predicates:
            - Path=/s2/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    instance-id: spring-cloud-gateway-server
    hostname: spring-cloud-gateway-server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway