server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: spring-cloud-eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8760

management:
  endpoints:
    web:
      exposure:
        include: "*"