server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          # 匹配所有请求
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - name: RateLimiter
          args:
            # 令牌桶每秒填充速率
            redis-rate-limiter.replenishRate: 1
            # 令牌桶总容量
            redis-rate-limiter.burstCapacity: 1
            # 每个请求从桶中取出的令牌数
            redis-rate-limiter.requestedTokens: 1
            # 限流用到的唯一键的解析器，使用SpEL表达式从Spring容器中获取Bean实例
            key-resolver: "#{@ipKeyResolver}"
            # 重新设置响应码为200
            status-code: OK
      routes:
        - id: spring-cloud-gateway-service-1
          uri: lb://spring-cloud-gateway-service-1
          predicates:
            - Path=/s1/**
          filters:
            - StripPrefix=1
        - id: spring-cloud-gateway-service-2
          uri: lb://spring-cloud-gateway-service-2
          predicates:
            - Path=/s2/**
          filters:
            - StripPrefix=1
    redis:
      host: localhost
      port: 6379
      database: 0
      # password:
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

eureka:
  instance:
    instance-id: spring-cloud-gateway-server
    hostname: spring-cloud-gateway-server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway