server:
  port: 8080
spring:
  application:
    name: grpc-nacos-client-sample
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
grpc:
  client:
    grpc-nacos-server-sample:
      negotiationType: plaintext