server:
  port: 8081
spring:
  application:
    name: okhttp-client-core
  cloud:
    openfeign:
      okhttp:
        # 开启okhttp client
        enabled: true
      httpclient:
        # 设置httpclient的连接超时时间，默认是2s
        connection-timeout: 2000
        # 设置连接池最大大小，默认200
        max-connections: 200
        ok-http:
          # 设置okhttp的全局读超时时间，默认是60s
          read-timeout: 60000
      client:
        config:
          # 单独设置某个服务的配置
          okhttp-server-core:
            # 设置连接超时时间为1s
            connect-timeout: 1000
            # 设置读超时时间为2s
            read-timeout: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

service:
  okhttp-server: okhttp-server-core
