version: "3.8"

# 定义网络：local_net
networks:
  local_net:
    name: local_net

# 定义服务
services:
  # zookeeper服务
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - local_net

  # kafka服务
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    networks:
      - local_net
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true